let Url = "http://localhost:8080";
window.movieApi = Url + "/movie/find-all";
window.ticketApi = Url + "/ticket/find-all";
window.seatApi = Url + "/seat/find-all";
window.seatTypeApi = Url + "/seat-type/find-all";
window.scheduleApi = Url + "/schedule/find-all";
window.roomApi = Url + "/room/find-all";
window.rankApi = Url + "/rank/find-all";
window.promotionApi = Url + "/promotion/find-all";
window.foodApi = Url + "/food/find-all";
window.customerApi = Url + "/customer/find-all";
window.cinemaApi = Url + "/cinema/find-all";
window.ratedApi = Url + "/rated/find-all";
window.generalSettingApi = Url + "/general-setting/find-all";
//add
window.addMovie = Url + "/movie/save";
window.addTicket = Url + "/ticket/save";
window.addSeat = Url + "/seat/save";
window.addSeatType = Url + "/seat-type/save";
window.addSchedule = Url + "/schedule/save";
window.addRoom = Url + "/room/save";
window.addRank = Url + "/rank/save";
window.addPromotion = Url + "/promotion/save";
window.addFood = Url + "/food/save";
window.addCustomer = Url + "/customer/save";
window.addCinema = Url + "/cinema/save";
//delete
window.deleteFood = Url + "/food/delete";
window.deleteCustomer = Url + "/customer/delete";
window.deleteCinema = Url + "/cinema/delete";
window.deleteRoom = Url + "/room/delete";
window.deleteSeat = Url + "/seat/delete";
window.deleteSeatType = Url + "/seat-type/delete";
window.deleteSchedule = Url + "/schedule/delete";
window.deleteRank = Url + "/rank/delete";
window.deletePromotion = Url + "/promotion/delete";
window.deleteTicket = Url + "/ticket/delete";
window.deleteMovie = Url + "/movie/delete";
//update
window.updateFood = Url + "/food/update";
window.updateCustomer = Url + "/customer/update";
window.updateCinema = Url + "/cinema/update";
window.updateRoom = Url + "/room/update";
window.updateSeat = Url + "/seat/update";
window.updateSeatType = Url + "/seat-type/update";
window.updateSchedule = Url + "/schedule/update";
window.updateRank = Url + "/rank/update";
window.updatePromotion = Url + "/promotion/update";
window.updateTicket = Url + "/ticket/update";
window.updateGenerralSettin = Url + "/generral-setting/update"
window.updateMovie = Url + "/movie/update";
//find by id
window.findTicket = Url + "/ticket/findById";
window.findSeat = Url + "/seat/findById";
window.findScedule = Url + "/seat/findById";
window.findRoom = Url + "/seat/findById";
window.findRated = Url + "/seat/findById";
window.findRank = Url + "/seat/findById";
window.findPromotion = Url + "/seat/findById";
window.findMovie = Url + "/seat/findById";
window.findGeneralSetting = Url + "/seat/findById";
window.findFood = Url + "/seat/findById";
window.findCinema = Url + "/seat/findById";
window.findBillTicket = Url + "/seat/findById";
window.findBillFood = Url + "/seat/findById";
window.findBill = Url + "/seat/findById";
window.findBill = Url + "/seat/findById";


